name: Build Windows Nunchuk App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t nunchuk-builder .

      - name: Extract build artifact
        run: |
          docker create --name temp-container nunchuk-builder
          docker cp temp-container:/nunchuk-windows.zip ./nunchuk-windows.zip
          docker rm temp-container

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nunchuk-windows
          path: ./nunchuk-windows.zip
